status = warn
name = PropertiesConfig

# Console appender
appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Root logger
rootLogger.level = info
rootLogger.appenderRef.stdout.ref = STDOUT

# Logger pour votre application
logger.parkit.name = com.parkit.parkingsystem
logger.parkit.level = debug
logger.parkit.additivity = false
logger.parkit.appenderRef.console.ref = STDOUT
